#!/bin/sh

set -e

case "$1" in
    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
    ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

# dh_makeshlibs omits the call to ldconfig (probably because the shared
# libraries do not have SONAME), so let's do it manually.
if [ "$1" = "remove" ]; then
	ldconfig
fi

exit 0
